// This file is @generated by prost-build.
/// ── ClientAuthentication ──────────────────────────────────────────────────
/// Socket.IO event: "client_authentication"
/// Direction: client → server
/// Observed wire (1080 bytes):
///    0a 14  \[20-byte ASCII token\]
///    12 06  "client"
///    1a 88 06  \[JWT, ~1050 bytes\]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ClientAuthentication {
    /// 20-char session token, e.g. "I47hvQfXx6SOPWD4bO00"
    #[prost(string, tag = "1")]
    pub token: ::prost::alloc::string::String,
    /// literal "client" in observed captures
    #[prost(string, tag = "2")]
    pub client_kind: ::prost::alloc::string::String,
    /// Bearer JWT for Prusa Connect auth
    #[prost(string, tag = "3")]
    pub access_jwt: ::prost::alloc::string::String,
}
/// ── Trigger ───────────────────────────────────────────────────────────────
/// Socket.IO event: "trigger"
/// Direction: client → server
/// Two triggers are sent after client_authentication:
///    Trigger 1: f1=1, f11=token   (hex prefix: 08 01 5a 14 ...)
///    Trigger 2: f2=1, f11=token   (hex prefix: 10 01 5a 14 ...)
/// Semantic: likely a camera-stream or feature-poll request.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Trigger {
    /// observed: 1 in first trigger; 0 in second  // observed: 0x08 0x01
    #[prost(uint32, tag = "1")]
    pub field1: u32,
    /// observed: 0 in first trigger; 1 in second  // observed: 0x10 0x01
    #[prost(uint32, tag = "2")]
    pub field2: u32,
    /// fields 3-10 not observed
    ///
    /// 20-char session token (field tag 0x5a)
    #[prost(string, tag = "11")]
    pub token: ::prost::alloc::string::String,
}
/// ── IceServer ─────────────────────────────────────────────────────────────
/// Sub-message within IceServerGroup.
/// Observed in WebRtcSignal.ice_config:
///    TURN example: f1=2, f2="coturn.prusa3d.com", f3=5349, f4=3
///    STUN example: f1=1, f2="stun.l.google.com",  f3=5349
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct IceServer {
    /// 1=STUN, 2=TURN, 3=TURNS (observed: 1 and 2)
    #[prost(uint32, tag = "1")]
    pub server_type: u32,
    #[prost(string, tag = "2")]
    pub host: ::prost::alloc::string::String,
    #[prost(uint32, tag = "3")]
    pub port: u32,
    /// 1=UDP, 2=TCP, 3=TLS; absent for STUN entries
    #[prost(uint32, tag = "4")]
    pub transport: u32,
}
/// ── IceServerGroup ────────────────────────────────────────────────────────
/// Groups TURN servers (with credentials) or STUN servers (no credentials).
/// Observed in WebRtcSignal f8 as repeated f1 submessages.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct IceServerGroup {
    #[prost(message, repeated, tag = "1")]
    pub servers: ::prost::alloc::vec::Vec<IceServer>,
    /// TURN username; absent for STUN groups
    #[prost(string, tag = "2")]
    pub username: ::prost::alloc::string::String,
    /// TURN password; absent for STUN groups
    #[prost(string, tag = "3")]
    pub credential: ::prost::alloc::string::String,
}
/// ── IceConfig ─────────────────────────────────────────────────────────────
/// Top-level ICE configuration payload in the initial WebRtcSignal from server.
/// Observed as field 8 of WebRtcSignal (199 bytes).
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct IceConfig {
    #[prost(message, repeated, tag = "1")]
    pub server_groups: ::prost::alloc::vec::Vec<IceServerGroup>,
    /// observed: 1
    #[prost(uint32, tag = "2")]
    pub field2: u32,
    /// observed: 300
    #[prost(uint32, tag = "3")]
    pub ttl_seconds: u32,
}
/// ── SdpBody ───────────────────────────────────────────────────────────────
/// Wraps an SDP offer or answer string.
/// Observed as field 4 of WebRtcSignal when msg_type in {1,2,3}.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SdpBody {
    /// full SDP text (RFC 4566)
    #[prost(string, tag = "1")]
    pub sdp: ::prost::alloc::string::String,
    /// media stream id, e.g. "0"
    #[prost(string, tag = "2")]
    pub mid: ::prost::alloc::string::String,
}
/// ── IceCandidateBody ──────────────────────────────────────────────────────
/// Wraps a single trickle-ICE candidate.
/// Observed as field 4 of WebRtcSignal when msg_type == 4.
/// f1 begins with "a=candidate:..." (RFC 5245 / RFC 8839 attribute line).
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct IceCandidateBody {
    /// "a=candidate:..." attribute line
    #[prost(string, tag = "1")]
    pub candidate: ::prost::alloc::string::String,
    /// media stream label, e.g. "video-stream"
    #[prost(string, tag = "2")]
    pub stream_id: ::prost::alloc::string::String,
}
/// ── WebRtcSignal ──────────────────────────────────────────────────────────
/// Socket.IO event: "webrtc"
/// Direction: bidirectional
///
/// Observed msg_type values:
///    1 = SDP_OFFER (server → client, initial offer with ICE config in f8)
///    2 = SDP_ANSWER (client → server or server → client)
///    3 = SDP_OFFER (client → server)
///    4 = ICE_CANDIDATE (trickle ICE, both directions)
///
/// Observed direction values (f7):
///    1 = originated by server / sent to client
///    2 = originated by client / sent to server
///
/// The body field (f4) varies by msg_type:
///    msg_type 1,2,3 → body contains SDP text (SdpBody)
///    msg_type 4     → body contains ICE candidate (IceCandidateBody)
///    msg_type 1 also includes f8 (IceConfig)
///
/// Because the body format is a tagged union, we store it as raw bytes here
/// so callers can decode based on msg_type. Typed accessors can be added
/// once the enum range is fully established.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WebRtcSignal {
    /// 20-char session token
    #[prost(string, tag = "1")]
    pub token: ::prost::alloc::string::String,
    /// Engine.IO session id of the *server* socket
    #[prost(string, tag = "2")]
    pub session_id: ::prost::alloc::string::String,
    /// session id or features-hash depending on direction
    #[prost(string, tag = "3")]
    pub peer_id: ::prost::alloc::string::String,
    /// SdpBody or IceCandidateBody encoded bytes
    #[prost(bytes = "vec", tag = "4")]
    pub body: ::prost::alloc::vec::Vec<u8>,
    /// see observed values above
    #[prost(uint32, tag = "5")]
    pub msg_type: u32,
    /// field 6 not observed
    ///
    /// 1=from_server, 2=from_client
    #[prost(uint32, tag = "7")]
    pub direction: u32,
    /// only present when msg_type == 1
    #[prost(message, optional, tag = "8")]
    pub ice_config: ::core::option::Option<IceConfig>,
}
/// ── CameraIdentity ────────────────────────────────────────────────────────
/// Camera device identity data. Observed as Status.identity.field1.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CameraIdentity {
    /// user-visible name, e.g. "IoThinkIFeelSoGood"
    #[prost(string, tag = "1")]
    pub camera_name: ::prost::alloc::string::String,
    /// "A8:B5:8E:97:AC:01"
    #[prost(string, tag = "2")]
    pub mac_address: ::prost::alloc::string::String,
    /// "10.99.50.34"
    #[prost(string, tag = "3")]
    pub ip_address: ::prost::alloc::string::String,
    /// field 4 not observed
    ///
    /// observed: 90 (decimal 'Z')
    #[prost(uint32, tag = "5")]
    pub field5: u32,
}
/// ── CameraIdentityOuter ───────────────────────────────────────────────────
/// One layer of wrapping around CameraIdentity (Status.field4).
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CameraIdentityOuter {
    #[prost(message, optional, tag = "1")]
    pub identity: ::core::option::Option<CameraIdentity>,
}
/// ── SysInfo ───────────────────────────────────────────────────────────────
/// Runtime/system information. Observed as Status.field9 (57 bytes).
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SysInfo {
    /// seconds since epoch (observed: i32 field)
    #[prost(fixed32, tag = "1")]
    pub uptime_epoch: u32,
    /// raw uptime in seconds
    #[prost(uint64, tag = "2")]
    pub uptime_seconds: u64,
    /// "0 days, 5:3:38"
    #[prost(string, tag = "3")]
    pub uptime_human: ::prost::alloc::string::String,
    /// "6.23,6.38,6.35,"
    #[prost(string, tag = "4")]
    pub load_avg: ::prost::alloc::string::String,
    /// observed: 35151872
    #[prost(uint64, tag = "5")]
    pub mem_total_kb: u64,
    /// observed: 1617920
    #[prost(uint64, tag = "6")]
    pub mem_free_kb: u64,
    /// observed: 167936
    #[prost(uint64, tag = "7")]
    pub mem_available_kb: u64,
    /// field 8 not observed
    ///
    /// integer CPU temp (observed: 115 → probably 11.5°C or 115 = raw)
    #[prost(uint32, tag = "9")]
    pub cpu_temp_int: u32,
}
/// ── StatusFlags ───────────────────────────────────────────────────────────
/// Small flag message. Observed as Status.field11 (2 bytes: 08 01).
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StatusFlags {
    /// observed: 1
    #[prost(uint32, tag = "1")]
    pub field1: u32,
}
/// ── CameraCapabilities ────────────────────────────────────────────────────
/// Camera firmware and capability details (Status.field5, 176 bytes).
/// Internal submessages still partially opaque; kept as bytes for now.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CameraCapabilities {
    /// "3.1.4"
    #[prost(string, tag = "1")]
    pub fw_version: ::prost::alloc::string::String,
    /// "NB.1.1.0"
    #[prost(string, tag = "2")]
    pub hw_version: ::prost::alloc::string::String,
    /// "Buddy3D Camera"
    #[prost(string, tag = "3")]
    pub camera_name: ::prost::alloc::string::String,
    /// observed: varint(2), str("UNKNOWN") — profile/type flags
    #[prost(bytes = "vec", tag = "4")]
    pub opaque_f4: ::prost::alloc::vec::Vec<u8>,
    /// field 5 not observed
    ///
    /// observed: varint(3), varint(2), str("rtsp://...") — stream config
    #[prost(bytes = "vec", tag = "6")]
    pub opaque_f6: ::prost::alloc::vec::Vec<u8>,
    /// observed: varint(2) — flags
    #[prost(bytes = "vec", tag = "7")]
    pub opaque_f7: ::prost::alloc::vec::Vec<u8>,
    /// field 8 not observed
    ///
    /// three strings: connect/signaling/ota hostnames
    #[prost(bytes = "vec", tag = "9")]
    pub opaque_f9: ::prost::alloc::vec::Vec<u8>,
}
/// ── Status ────────────────────────────────────────────────────────────────
/// Socket.IO event: "status"
/// Direction: server → client
/// Observed frame: 492 bytes
///
/// Top-level field layout (verified from wire):
///    f2  = opaque protocol config (13 bytes submsg)
///    f3  = opaque flags (8 bytes submsg)
///    f4  = CameraIdentityOuter (56 bytes)
///    f5  = CameraCapabilities (176 bytes)
///    f8  = token string
///    f9  = SysInfo (57 bytes)
///    f10 = camera_id string
///    f11 = StatusFlags
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Status {
    /// field 1 not observed
    ///
    /// protocol config blob (observed: 13 bytes)
    #[prost(bytes = "vec", tag = "2")]
    pub opaque_f2: ::prost::alloc::vec::Vec<u8>,
    /// flags blob (observed: 8 bytes)
    #[prost(bytes = "vec", tag = "3")]
    pub opaque_f3: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag = "4")]
    pub identity: ::core::option::Option<CameraIdentityOuter>,
    #[prost(message, optional, tag = "5")]
    pub capabilities: ::core::option::Option<CameraCapabilities>,
    /// fields 6, 7 not observed
    ///
    /// 20-char session token
    #[prost(string, tag = "8")]
    pub token: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "9")]
    pub sys_info: ::core::option::Option<SysInfo>,
    /// "SK1_Gy4shE_GJ7AbP8BS" — printer/camera serial?
    #[prost(string, tag = "10")]
    pub camera_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "11")]
    pub flags: ::core::option::Option<StatusFlags>,
}
/// ── Features ─────────────────────────────────────────────────────────────
/// Socket.IO event: "features"
/// Direction: server → client
/// Observed frame: 500 bytes
///
/// Field layout (verified from wire):
///    f2  = token
///    f3  = fw_version
///    f4  = hw_version
///    f5  = schema_version ("4.4")
///    f6  = features_json (JSON array of feature-name strings)
///    f7  = features_hash (MD5 hex of features set?)
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Features {
    /// field 1 not observed
    ///
    /// 20-char session token
    #[prost(string, tag = "2")]
    pub token: ::prost::alloc::string::String,
    /// "3.1.4"
    #[prost(string, tag = "3")]
    pub fw_version: ::prost::alloc::string::String,
    /// "NB.1.1.0"
    #[prost(string, tag = "4")]
    pub hw_version: ::prost::alloc::string::String,
    /// "4.4"
    #[prost(string, tag = "5")]
    pub schema_version: ::prost::alloc::string::String,
    /// JSON-encoded array of feature-name strings
    #[prost(string, tag = "6")]
    pub features_json: ::prost::alloc::string::String,
    /// hex string, e.g. "cf9477d9e9568d62e75c265872c477c8"
    #[prost(string, tag = "7")]
    pub features_hash: ::prost::alloc::string::String,
}
